//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_blacktile_H
#define METASPRITE_blacktile_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define blacktile_TILE_ORIGIN 0
#define blacktile_TILE_W 8
#define blacktile_TILE_H 8
#define blacktile_WIDTH 8
#define blacktile_HEIGHT 8
#define blacktile_TILE_COUNT 1

BANKREF_EXTERN(blacktile)

extern const uint8_t blacktile_tiles[16];

#endif
