//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_blanktile_H
#define METASPRITE_blanktile_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define blanktile_TILE_ORIGIN 0
#define blanktile_TILE_W 8
#define blanktile_TILE_H 8
#define blanktile_WIDTH 8
#define blanktile_HEIGHT 8
#define blanktile_TILE_COUNT 1

BANKREF_EXTERN(blanktile)

extern const uint8_t blanktile_tiles[16];

#endif
